#GET https://wechat.fangpinduo.com/api/get_countries HTTP/1.1


#GET https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wx3c36a7bbdf1f0793&secret=f726f017e1ca93e90313a3369e2d133c HTTP/1.1

POST https://api.weixin.qq.com/wxa/getwxacode?access_token=19_bviYl-qnDmIKFNufoRpA9nyJ0ulb7LURj10TuBSF_aZiYnFucOp2JUz0iA2LqNNOJY0CUpYN5KyR7q5g-xYk9liRklc4NWSHxEhTrgZCVdhSel94uTTirsDSfQQTOGiAIAAVN HTTP/1.1
Content-Type: application/json

{
   "path":"pages/home/home"
}